# GitHub Actions Workflow for Code Quality

name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check
    
    - name: Run Clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Run security audit
      run: |
        cargo install cargo-audit
        cargo audit