# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[graph]
all-features = true

[output]
feature-depth = 1

[advisories]
yanked = "deny"
ignore = [
    # List any advisories that should be ignored
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]