[env]
RUST_BACKTRACE = "1"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "-D", "warnings"]

[tasks.doc]
command = "cargo"
args = ["doc", "--no-deps", "--all-features"]

[tasks.check]
command = "cargo"
args = ["check", "--all-features"]

[tasks.check-all]
command = "cargo"
args = ["check", "--all-features", "--all-targets"]

[tasks.audit]
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]

[tasks.deny]
install_crate = "cargo-deny"
command = "cargo"
args = ["deny", "check"]

[tasks.ci]
dependencies = [
    "format",
    "check-all",
    "clippy",
    "test",
    "doc"
]

[tasks.release]
dependencies = [
    "clean",
    "check-all",
    "clippy",
    "test-release",
    "build-release"
]