[package]
name = "cross-asset-latency-lead"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
hft-common = { path = "../hft-common" }
anyhow = "1.0"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
